spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:29092

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: halcyon.ruslan@gmail.com
    password: hifl fxfp brqz oavf
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true