spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: ${DOCKER_KAFKA_BOOTSTRAP_SERVERS}

  mail:
    protocol: ${MAIL_PROTOCOL}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: ${DOCKER_EUREKA_CLIENT_DEFAULT_ZONE}
    fetch-registry: true
    register-with-eureka: true
    enabled: true