spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-controller
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        - id: subscription-controller
          uri: lb://user-service
          predicates:
            - Path=/api/v1/subscriptions/**

        - id: strike-controller
          uri: lb://user-service
          predicates:
            - Path=/api/v1/strikes/**

        - id: auth-controller
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: oauth2-controller
          uri: lb://auth-service
          predicates:
            - Path=/oauth2/**

        - id: post-controller
          uri: lb://media-service
          predicates:
            - Path=/api/v1/posts/**

        - id: comment-controller
          uri: lb://media-service
          predicates:
            - Path=/api/v1/comments/**

        - id: message-controller
          uri: lb://chat-service
          predicates:
            - Path=/api/v1/messages/**

server:
  port: 9191

eureka:
  client:
    service-url:
      defaultZone: ${DOCKER_EUREKA_CLIENT_DEFAULT_ZONE}
    fetch-registry: true
    register-with-eureka: true
    enabled: true