spring:
  application:
    name: user-service

  config:
    import: optional:file:.env[.properties]

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  liquibase:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_DEFAULT_ZONE}
    fetch-registry: true
    register-with-eureka: true
    enabled: true

jwt:
  issuer: jwt-library
  access-token:
    private-key: ${PRIVATE_KEY}
    public-key: ${PUBLIC_KEY}
    validity: ${ACCESS_TOKEN_VALIDITY}

private:
  secret: ${PRIVATE_SECRET}

file:
  storage:
    location: ${FILE_STORAGE_LOCATION}