spring:
  application:
    name: chat-service

  liquibase:
    enabled: true

  data:
    redis:
      host: ${DOCKER_REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

  datasource:
    url: ${DOCKER_POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: ${DOCKER_EUREKA_CLIENT_DEFAULT_ZONE}
    fetch-registry: true
    register-with-eureka: true
    enabled: true

jwt:
  issuer: jwt-library
  access-token:
    private-key: ${PRIVATE_KEY}
    public-key: ${PUBLIC_KEY}
    validity: ${ACCESS_TOKEN_VALIDITY}

private:
  secret: ${PRIVATE_SECRET}